version: '3.8'

services:
  ###> webserver image Nginx ###
  ###> webserver image Nginx ###
  webserver:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./:/var/www/html

  php:
    build: ./docker/php/
    expose:
      - "9000"
    volumes:
      - .:/var/www/html

  ###> doctrine/doctrine-bundle ###
  db:
    image: mariadb:latest
    platform: linux/x86_64
    container_name: database_eterno
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_eterno
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
    ports:
      - "3306:3306"
  ###< doctrine/doctrine-bundle ###

  ###> phpMyAdmin ###
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_eterno
    restart: always
    depends_on:
      - db
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
    networks:
      - dev
  ###< phpMyAdmin ###

  ###> MailDev ###
  maildev:
    image: maildev/maildev
    container_name: maildev_eterno
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    # MAILER_DSN=smtp://127.0.0.1:1025
    ports:
      - "8081:80"
      - "1025:25"
    restart: always
    networks:
      - dev
###< MailDev ###

networks:
  dev:

volumes:
  db-data:
